# Generated by Django 4.0.5 on 2022-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_id',
            field=models.PositiveIntegerField(default=1, verbose_name='icon id'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='sort index'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to='catalog/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
