# Generated by Django 4.0.5 on 2022-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_category_icon_id_category_sort_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
