# Generated by Django 4.0.5 on 2022-08-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount in %'),
        ),
    ]
