# Generated by Django 4.0.5 on 2022-08-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_alter_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_item', to='app_catalog.media', verbose_name='cover image'),
        ),
    ]
