# Generated by Django 4.0.5 on 2022-08-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0006_alter_item_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='app_catalog.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='app_catalog.parameter', verbose_name='parameter'),
        ),
    ]
