# Generated by Django 4.0.5 on 2022-07-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='user',
        ),
        migrations.AddField(
            model_name='usermedia',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to=settings.AUTH_USER_MODEL, verbose_name='uploader'),
            preserve_default=False,
        ),
    ]
