# Generated by Django 4.0.5 on 2022-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_usermedia_user_usermedia_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='phone number'),
        ),
    ]
